sudo: required

language: python

services:
  - docker

before_install:
- docker pull lins05/seafile-debian-builder
- |
  docker run --rm -it \
        -e BINTRAY_AUTH:$BINTRAY_AUTH \
        -e TRAVIS_TAG:$TRAVIS_TAG \
        -e TRAVIS_BRANCH:$TRAVIS_BRANCH \
        -e TRAVIS_PULL_REQUEST:$TRAVIS_PULL_REQUEST \
        -v `pwd`:/app \
        --name builder \
        lins05/seafile-debian-builder \
        /app/build.sh
